vich_uploader:
  db_driver: orm

  mappings:
    projects:
      uri_prefix: /images/projects
      upload_destination: "%kernel.project_dir%/public/images/projects"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    articles:
      uri_prefix: /images/articles
      upload_destination: "%kernel.project_dir%/public/images/articles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
